spring:
  application:
    name: small-demo-kotlin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.118.28.180:3306/test?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xhh1999.02.10
  redis:
    host: 47.118.28.180
    port: 6379
    password: xhh1999.02.10
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-wait: 1000
        max-idle: 8
        min-idle: 0